version: "3.9"

services:
  database:
    image: postgres
    container_name: database_gymstations
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gymstations_app
    volumes:
      - pgdata:/data/postgres
  database_test:
    image: postgres
    container_name: database_gymstations_test
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: docker_test
      POSTGRES_PASSWORD: password_test
      POSTGRES_DB: gymstations_app_test
    volumes:
      - pgdata_test:/data/postgres
  app:
    build: .
    container_name: gymstations_app
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local
  pgdata_test:
    driver: local